#!/bin/sh
### BEGIN INIT INFO
# Provides:          iptables
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6 
# Short-Description: Iptables rules
### END INIT INFO

RULES=/etc/iptables.rules

if [ ! -f $RULES ]
then
	iptables-save -c > $RULES
fi

. /lib/lsb/init-functions

case "$1" in
start|restart|reload|force-reload)
	log_daemon_msg "Starting iptables" "iptables"
	iptables-restore -c < $RULES
	log_end_msg $?
	;;
stop)
	log_daemon_msg "Stopping iptables" "iptables"
	iptables-save -c > $RULES
	for t in filter nat mangle
	do
		iptables -t $t -F
		iptables -t $t -Z
	done

	iptables -P FORWARD ACCEPT
	iptables -P INPUT ACCEPT
	iptables -P OUTPUT ACCEPT

	log_end_msg 0
	;;
status)
	for t in filter nat mangle
	do
		echo $t':'
		iptables -t $t -L
	done
	;;
save)
	log_daemon_msg "Staving iptables" "iptables"
	iptables-save -c > $RULES
	log_end_msg $?
	;;
*)
	echo "Usage: service iptables "'{start|stop|status|save}'
esac
